미야 로그 기능 추가
LRACT/Miya pull request #13
Opened 2020-09-17 05:42 UTC by ArceRoot

#12 와 관련됨
완료되면 리뷰하고 Merge.

2020-09-17 13:28 UTC, SaidBySolo commented on utils/team.py
> +    return owner
데코레이터로 짤래?

2020-09-17 13:29 UTC, SaidBySolo commented on utils/team.py
> +    return owner
아니근데 너무 비효율적인데 저거

2020-09-17 13:29 UTC, SaidBySolo commented on utils/team.py
> +    return owner
굳이 팀멤버 확인해야하는 이유 서술

2020-09-18 01:03 UTC, ArceRoot commented on utils/team.py
> +    return owner
기본적으로 우리가 팀이라서 팀 멤버를 확인하는 거고
저건 오너를 확인할 수 있는 다른 방법이 있으면 바꿔도 상관 없음.
당장은 관리자 확인을 대충이라도 해야되니까 적어놓은 거

2020-09-18 03:16 UTC, SaidBySolo commented on utils/team.py
> +    return owner
owners_id

2020-09-18 03:38 UTC, ArceRoot commented on utils/team.py
> +    return owner
그거 되는지 안되는지 모르겠음

2020-09-18 03:38 UTC, ArceRoot commented on utils/team.py
> +    return owner
굳이 뭐 누가 보는것도 아닌데 그냥 둬도 될 거 같기도

2020-09-27 13:28 UTC, SaidBySolo requested changes

2020-09-27 13:28 UTC, SaidBySolo commented on modules/events.py
> +                p = "관리자"
dict 사용해서 묶어버리세요.

2020-09-27 13:28 UTC, SaidBySolo commented on modules/events.py
> +            if mp[0] == "manage_webhooks":
위에꺼 묶은걸로 사용하면될듯

2020-09-27 13:28 UTC, SaidBySolo commented on modules/events.py
> +            if ctx.command.name == "차단":
다중if 웬만하면 사용 X elif 사용

아니면 저것도 dict묶던가

2020-09-28 06:14 UTC, ArceRoot commented on modules/events.py
> +            if ctx.command.name == "차단":
그거 좋은 생각인듯

2020-09-28 07:25 UTC, ArceRoot commented on modules/events.py
> +                p = "관리자"
해결

2020-09-28 07:31 UTC, SaidBySolo submitted a review, later dismissed
LGFM

2020-09-28 07:34 UTC, ArceRoot commented
그럼 뮤트 기능까지만 만들고 머지하는 걸로

2020-09-28 08:47 UTC, CwhiteKJ reviewed
역할이 존재하지 않을 시 채널 설정으로 메세지 전송을 막거나 역할을 생성하는건 어떰?

2020-09-28 08:48 UTC, ArceRoot commented
> 역할이 존재하지 않을 시 채널 설정으로 메세지 전송을 막거나 역할을 생성하는건 어떰?

그거 역할설정 명령어 만들어서 해결함

2020-09-28 08:49 UTC, CwhiteKJ submitted a review, later dismissed

2020-09-28 08:59 UTC, SaidBySolo requested changes

2020-09-28 08:59 UTC, SaidBySolo commented on requirements.txt
>  asyncio
기본모듈

2020-09-28 09:00 UTC, ArceRoot commented on requirements.txt
>  asyncio
뭐 aiosqlite?
저건 기본모듈 아닌데

2020-09-28 09:01 UTC, CwhiteKJ commented on requirements.txt
>  asyncio
asyncio 얘기하는거 아님?

2020-09-28 09:01 UTC, ArceRoot commented on requirements.txt
>  asyncio
asyncio도 기본모듈 아님

2020-09-28 09:05 UTC, SaidBySolo commented on requirements.txt
>  asyncio
내장모듈이에요^^

2020-09-28 09:08 UTC, ArceRoot commented on requirements.txt
>  asyncio
정확하게 무슨 모듈을 말하는건가요

2020-09-28 09:12 UTC, CwhiteKJ commented on modules/mods.py
> +    @commands.has_permissions(manage_roles=True)
여기 중복되는 구문이 있는데 의도가 뭔가요

2020-09-28 09:13 UTC, ArceRoot commented on modules/mods.py
> +    @commands.has_permissions(manage_roles=True)
아 bot_has_permissions인데 오타입니다

2020-09-28 09:13 UTC, CwhiteKJ commented on modules/mods.py
> +    @commands.has_permissions(manage_roles=True)
아래 슬로우모드 쪽 구문에도 같은 실수가 있네요

2020-09-28 09:14 UTC, CwhiteKJ approved these changes

2020-09-28 09:16 UTC, CwhiteKJ submitted a review, later dismissed

2020-09-28 09:18 UTC, ArceRoot commented on requirements.txt
>  asyncio
너무 지체되어 리뷰를 닫습니다. 문제가 있을 시 이슈 남겨주세요.

2020-09-28 09:34 UTC, merged